### PR TITLE
Judah/img upload

### PR DESCRIPTION
**Pull request by judahkrug**
Image Upload Endpoint with Azure. The endpoint should be working as long as the user can put the Azure SAS key into their dotenv file.

### CODE REVIEW

**Review by ML-Chen — CHANGES_REQUESTED** [review]
Can you add the environment variable name for the Azure SAS key in .env.example? I'll look over this pull request some more later today or tomorrow.

**Comment by ML-Chen** [comment]
Can you create an Express endpoint in src/controllers accepting a multipart/form-data request which has image data, and then uploads this image to Azure? Something like https://attacomsian.com/blog/uploading-files-nodejs-express

**Comment by ML-Chen** [comment]
Can you add some comment with links to the relevant webpages that this code is drawn from? I honestly don't understand what much of this code is supposed to do, and I think adding some links would really help other people (who might not be familiar with Azure) with understanding it.

**Review by judahkrug — COMMENTED** [review]
Reviewed

**Review by ML-Chen — CHANGES_REQUESTED** [review]
Try to get postImage to include the URL of the image that is uploaded.

**Pull request merged**
